# Generated by Django 4.2.1 on 2023-07-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IvatMaslov', '0002_famous_info_rap'),
    ]

    operations = [
        migrations.CreateModel(
            name='look',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=70)),
            ],
        ),
        migrations.RenameField(
            model_name='famous',
            old_name='squad',
            new_name='squade',
        ),
    ]
